# Intro to Numpy

## Arrays Introduction

In [2]:
import numpy as np

In [44]:
# Declaring Arrays
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [13]:
# Declaring 2D array
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

### Accessing Array elements

In [19]:
# Printing specific elements
# array[row, column] for 2D Array
arr[1,2]

6

In [35]:
# Full row array[row, : ]
arr[1, : ]

array([4, 5, 6])

In [39]:
# Full column array[ :, column]
arr[:, 2]

array([3, 6])

### Slicing in Array

In [46]:
# array[row : column]
a[1:4]

array([2, 3, 4])

In [47]:
# Identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [59]:
# Copying array
array2 = np.copy(arr)
# here array2 will elements will change
array2[0,2] = 5
array2[0,1] = 11


### Arthemetic Operations

In [71]:
# addition
arr + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [66]:
# subtraction
a - 2

array([-1,  0,  1,  2])

In [67]:
# multiplication
a * 2

array([2, 4, 6, 8])

In [70]:
# division
arr / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

### Trignometric Operations

In [73]:
# sin, cos, tan, log, exp ETC.
np.sin(arr)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [75]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

## List Introduction

In [76]:
lst = [1,2,3,4,5]
lst

[1, 2, 3, 4, 5]

In [94]:
# You cannot perform arthemetic operations on list type.
# Convert list to array if you want to do so
converted = np.array(lst)
type(converted)

numpy.ndarray

In [96]:
# Operations on Converted list --> Array
np.sin(converted)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])