# Data Generation with numpy

In [1]:
import numpy as np

### Basic Operations on matrix

In [57]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
# minimum value in matrix
arr.min()

1

In [45]:
# maximum value in matrix
arr.max()

9

In [49]:
# min & max index of min or max value
arr.argmax()
#arr.argmin()

8

In [52]:
# getting the shape of matrix (order)
# 2 ways i.e. np.shape(arr) or arr.shape
arr.shape

(3, 3)

In [59]:
# Reshaping the array
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [63]:
# determinant of matrix
# Note: det is only possible for square matrix i.e. rows == columns
a = np.array([[2,2],[3,4]])
np.linalg.det(a)

1.9999999999999998

## Standard deviation & Variance

In [65]:
# Most important factors in ML
# standard deviation
np.std(a)

0.82915619758885

In [66]:
# variance
np.var(a)

0.6875

### Data generation

In [9]:
# array of zeros
arr = np.zeros((4, 3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# array of ones
a = np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [14]:
# array of any other number
a = np.full((3,3), 1)
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### Generating Random Numbers

In [16]:
# Uniform distribution as the numbers will be from 0-1
randomArr = np.random.rand(2, 3)
randomArr

array([[0.43071065, 0.84301591, 0.76398993],
       [0.73464353, 0.0048882 , 0.16266771]])

In [17]:
# Normal distribution as the numbers will be from -1 to 1
rArr = np.random.randn(2,3)
rArr

array([[-0.10233835,  0.05794817,  0.30631827],
       [ 0.53138366, -0.80555548,  1.847212  ]])

In [18]:
# Random integers
# np.random.radnin(startingNumber, endingNumber, arraySize)
arr = np.random.randint(0, 10, size=(2,2))
arr

array([[8, 7],
       [0, 1]])

### Matrix Multiplication

In [24]:
# Generic Rule as in Matrix Multiplication i.e. (2,3) x (3,4) Here inner pair is equal i.e 3 x 3
# But, (2,1) x (2,1) won't multiply
mat1 = np.array([[1,2], [3,4], [6,7]])
mat2 = np.array([[8,7,6],[5,4,3]])

# Hint: To avoid mistake, first print he shape of matrix i.e. np.shape(mat1)
# Matrix follow DOT multiplication
mulResult = np.dot(mat1, mat2)
mulResult

array([[18, 15, 12],
       [44, 37, 30],
       [83, 70, 57]])

In [29]:
# aranging the order
arr = np.arange(-1,10)
arr

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [33]:
# aranging the order with stepsize i.e. np.arange(start, end, stepSize)
arr = np.arange(0, 20, 5)
arr

array([ 0,  5, 10, 15])

### Linespace

In [41]:
# Dividing a given range into specific intervals i.e. np.linspace(start, end, intervals)
linspace = np.linspace(0, 10, 25)
linspace

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])